export const userConstants = {
LOGOUT: 'LOGOUT',
USERCREDENTIALS:{
    SHOW: 'SHOW',
    HIDE: 'HIDE',
    ADD_DATA: 'ADD_DATA',
    EDIT_DATA: 'EDIT_POPUP',
    UPDATE_DATA: 'UPDATE_DATA',
    CLIENTDETAILS:'CLIENTDETAILS',
    VIEW_DATA: 'VIEW_DATA',
    SET_DATA:'SET_DATA',
    NEW_RECORD: 'ADD_NEW_TABLE_RECORD'
}
}